version: '3'
services:

  nginx:
    image: nginx:alpine
    hostname: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./_site/www:/srv/site
      - xhgui-volume:/srv/xhgui
    ports:
      - ${PORT_NGINX}:80
      - ${PORT_XHGUI}:81
    command: /bin/sh -c "exec nginx -g 'daemon off;'"

  apache:
    build: ./apache
    hostname: apache
    volumes:
      - ./apache/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./_site/www:/var/www/site
      - xhgui-volume:/var/www/xhgui
    environment:
      TZ: ${TZ}
      XHGUI_MONGO_HOST: "mongodb://mongo:27017"

  mysql:
    image: mysql:5.7.28
    hostname: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: ${TZ}
    volumes:
      - ./mysql/var:/var/lib/mysql
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  mongo:
    image: mongo
    hostname: mongo
    restart: always

  adminer:
    image: adminer
    hostname: adminer
    restart: always
    ports:
      - ${PORT_ADMINER}:8080
    depends_on:
      - mysql
    environment:
      TZ: ${TZ}

  tools:
    build: ./tools
    hostname: tools
    volumes:
      - ./_logs:/srv/_logs
    environment:
      TZ: ${TZ}

volumes:
  xhgui-volume:
